"""Generate the hyperparameter table for the runs of the evaluation table.

Usage:
    python scripts/generate_hyperparameter_table.py
        [--config results/hyperparameter_config.yaml]
        [--out results/tables/hyperparameter-table.tex] [--experiment NAME]

The columns come from ``--config``; the rows are the runs of the NRMSE table,
picked from the config's ``results_config`` by the same selection
(scripts/generate_eval_table.py:iter_best_runs), so both tables describe the
same runs. Unlike the NRMSE table this is ONE table over every stability class:
hyperparameters are comparable across all benchmarks.
"""

import argparse
import logging
import sys
from pathlib import Path

from generate_eval_table import ConfigLoader, iter_best_runs, project_root

from sysid.reporting.eval_table import load_table_config
from sysid.reporting.hyperparameter_table import (
    HyperRow,
    build_hyperparameter_table,
    load_hyperparameter_config,
    needs_logged_config,
    row_values,
)

DEFAULT_CONFIG = "results/hyperparameter_config.yaml"
DEFAULT_OUT = "results/tables/hyperparameter-table.tex"

logger = logging.getLogger("generate_hyperparameter_table")


def _resolve(path: str) -> Path:
    out = Path(path)
    return out if out.is_absolute() else project_root() / out


def build_rows(results_config, columns, only=None):
    rows = []
    with_config = needs_logged_config(columns)
    loader = ConfigLoader()
    for experiment, model_name, best, note in iter_best_runs(results_config, only):
        name = experiment["mlflow_experiment_name"]
        if best is None:
            rows.append(
                HyperRow(experiment["name"], model_name, mlflow_experiment_name=name, note=note)
            )
            continue
        run_id = best["run_id"]
        run_config = loader(run_id) if with_config else None
        values = row_values(columns, model_name, best, run_config)
        missing = [label for label, v in values.items()
                   if v is None and not any(
                       c["label"] == label and model_name in c["blank_for"] for c in columns)]
        logger.info("  %-7s %s  %s", model_name, run_id,
                    ", ".join(f"{k}={v}" for k, v in values.items()))
        rows.append(
            HyperRow(
                experiment["name"],
                model_name,
                run_id=run_id,
                mlflow_experiment_name=name,
                values=values,
                note=f"not logged: {', '.join(missing)}" if missing else None,
            )
        )
    return rows


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default=DEFAULT_CONFIG, help="column layout YAML")
    parser.add_argument(
        "--results-config",
        help="experiment layout YAML; defaults to the column YAML's results_config",
    )
    parser.add_argument("--out", default=DEFAULT_OUT, help="LaTeX output path")
    parser.add_argument(
        "--significant-digits", type=int, default=3,
        help="significant figures for the 'sig' columns (sampling time)",
    )
    parser.add_argument("--experiment", help="only this experiment (name or MLflow name)")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s", stream=sys.stdout)

    config_path = _resolve(args.config)
    hp_config = load_hyperparameter_config(config_path)
    results_path = _resolve(
        args.results_config or hp_config["results_config"] or "results/results_confg.yaml"
    )
    results_config = load_table_config(results_path)

    rows = build_rows(results_config, hp_config["columns"], args.experiment)
    if not rows:
        logger.error("no rows produced -- nothing written")
        return 1

    tex = build_hyperparameter_table(
        rows,
        hp_config["columns"],
        comment=(
            f"generated by scripts/generate_hyperparameter_table.py from "
            f"{config_path.name} + {results_path.name}; same runs as the eval table"
        ),
        significant_digits=args.significant_digits,
    )
    out_path = _resolve(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(tex + "\n")
    logger.info("\nSaved %s\n\n%s", out_path, tex)

    incomplete = [r for r in rows if r.note]
    if incomplete:
        logger.warning(
            "\n%d row(s) incomplete:\n%s",
            len(incomplete),
            "\n".join(f"  {r.experiment} / {r.model_name}: {r.note}" for r in incomplete),
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
