"""THE SANITY GATE: a warm-started model must converge back to the model that
generated the data.

This is a slow end-to-end test, closer to ``test_scripts_smoke`` than to a unit
test, and it is deliberately the strongest statement in the suite:

    Data is generated by a known Lure system. The model is initialized AT that
    system, perturbed slightly, and projected back onto the certified set. A few
    epochs of training must then drive the prediction loss back down to the level
    the generating parameters themselves achieve.

If that fails, the training loop is wrong — not the initialization, not the model
class, not the data. There is nothing left to blame: the optimum is known, it is
representable, and the run starts next to it.

Hermetic: the reference system and the .npz are built here, so the test does not
depend on ~/genSecSysId-Data. Its settings come from the checked-in
``tests/resoruces/sanity_gate.yaml`` — deliberately NOT the working config, which
is a live experiment; the gate has to be a fixed reference point. That file also
carries the reasoning for the two hyperparameters that differ from the Duffing
configs.

Every training run is logged to MLflow under the ``crnn-sanity_gate`` experiment —
the gate itself plus the two known-limitation variants — so the loss curves and the
distance-to-reference are inspectable next to real runs instead of collapsing to a
pass/fail line. The ``gate`` run carries ``gate_passed`` and ``best_over_true``.
Set ``SYSID_SANITY_MLFLOW=0`` to disable (e.g. in CI).

Note on the learning rate. This runs at a much smaller lr than the Duffing configs
use, and that is a real finding rather than test-tuning: Adam's step is ~lr per
element regardless of that element's scale, so with B entries ~5e-3 and rho(A)
within ~6e-3 of the unit circle, an lr of 5e-3 moves A straight out of the stable
region on the first step and the rollout explodes. See TestLearningRateSensitivity.
"""

import contextlib
import os
from pathlib import Path

from dataclasses import replace

import numpy as np
import pytest
import torch

from sysid.config import Config
from sysid.data import create_dataloaders
from sysid.evaluation import Evaluator
from sysid.models.constrained_rnn import SimpleLure
from sysid.training import Trainer, get_loss_function, get_optimizer

from tests.solver_utils import requires_mosek

pytestmark = requires_mosek

# Everything the gate runs at comes from a CHECKED-IN config, not from constants
# here and not from the working config in genSecSysId-Data. That file is a live
# experiment; the gate has to be a fixed reference point. Loading it through the
# real Config also means a renamed or dropped field fails the gate instead of being
# silently ignored.
CONFIG_PATH = Path(__file__).parent / "resoruces" / "sanity_gate.yaml"
CFG = Config.from_yaml(str(CONFIG_PATH))

ND, NE = 1, 1
NX, NW = CFG.model.nx, CFG.model.nw
TS = CFG.data.sampling_time
SEQ_LEN = CFG.data.train_sequence_length
WARMUP = CFG.training.warmup_steps

# Reference-system shape. Chosen so the fixture has the properties the gate needs —
# see _reference_system for what each one buys and how it was measured.
DAMPING = 2.0                 # -> rho(A) = 0.95
BP_LO, BP_HI = 0.05, 1.2      # dead-zone breakpoints, geometrically spaced
NL_GAIN, NL_POWER = 6.0, 3.0  # -> rho(A + B2 C2) = 1.14, escape outside the band
CONV_AMP, X0_AMP = 1.0, 0.2   # converging split: ~20% firing, no escapes
DIV_AMP = 4.0                 # diverging split: escapes from x0 = 0
DIVERGENCE_CAP = 50.0         # stop recording once the state clearly escapes;
                              # keeps max|y| ~50x the converging range, as in the
                              # real split (21.2 vs 0.555)
N_TRAJ, N_DIV_TRAJ, N_STEPS = 8, 6, 600


def _reference_system():
    """A Lure system that is stable in the dead band and UNSTABLE outside it.

    This is the structure that makes the whole exercise meaningful, and it mirrors
    the Duffing reference:

        rho(A)         = 0.95   -> inside the band the model is a damped oscillator
        rho(A + B2 C2) = 1.14   -> with the dead zone fully active it diverges

    (the Duffing reference is 0.9937 / 1.109). Without the second property no input
    could ever produce a diverging trajectory, and the diverging half of the gate
    would be vacuous — an earlier version of this fixture had rho(A + B2 C2) = 0.95
    and was silently globally stable.

    The nonlinearity is a staggered-breakpoint dead zone, again as in the Duffing
    model: unit i fires once |q| > bp_i, and its gain grows like bp_i^3, so the
    earliest-firing units barely perturb the dynamics while the late ones drive the
    escape. That graded structure is what lets ordinary trajectories exercise the
    nonlinearity (~20% of (step, unit) pairs fire) without being dragged out of the
    stable region.
    """
    bp = np.geomspace(BP_LO, BP_HI, NW)
    C2 = np.zeros((NW, NX)); C2[:, 0] = 1.0 / bp
    B2 = np.zeros((NX, NW)); B2[1, :] = TS * NL_GAIN * bp ** NL_POWER
    return {
        "A": np.eye(NX) + TS * np.array([[0.0, 1.0], [-1.0, -DAMPING]]),
        "B": TS * np.array([[0.0], [1.0]]),
        "B2": B2,
        "C": np.array([[1.0, 0.0]]),
        "C2": C2,
        "D": np.zeros((NE, ND)),
        "D12": np.zeros((NE, NW)),
        "D21": np.zeros((NW, ND)),
        "nx": NX, "nz": NW, "nu": ND, "ny": NE,
    }


def _simulate(ref, u, x0, cap=DIVERGENCE_CAP):
    """Roll the reference Lure system: x+ = Ax + Bu + B2*dzn(C2 x + D21 u).

    Stops early once the state passes ``cap``, the way the real diverging splits are
    recorded — they hold the approach to the escape, not the overflow after it.
    Returns ``(y, x, diverged)``.
    """
    n = len(u)
    x = np.asarray(x0, dtype=float).reshape(NX)
    y, xs = np.zeros((n, NE)), np.zeros((n, NX))
    for k in range(n):
        xs[k] = x
        uk = u[k].reshape(ND)
        z = ref["C2"] @ x + ref["D21"] @ uk
        w = z - np.clip(z, -1.0, 1.0)          # dead zone
        y[k] = ref["C"] @ x + ref["D"] @ uk + ref["D12"] @ w
        x = ref["A"] @ x + ref["B"] @ uk + ref["B2"] @ w
        if not np.isfinite(x).all() or np.abs(x).max() > cap:
            return y[: k + 1], xs[: k + 1], True
    return y, xs, False


def _converging_set(ref, n_traj, seed):
    """Ordinary trajectories: moderate input, non-zero x0, none of them escape.

    Returns (inputs, outputs, states) with the FULL state trajectory, matching what
    the CSV loader produces from state_col — the dataset asserts states and inputs
    share a sequence length.
    """
    rng = np.random.default_rng(seed)
    U, Y, X = [], [], []
    while len(U) < n_traj:
        u = CONV_AMP * rng.standard_normal((N_STEPS, ND))
        y, xs, diverged = _simulate(ref, u, X0_AMP * rng.standard_normal(NX))
        if diverged:
            continue                            # keep the converging split converging
        U.append(u); Y.append(y); X.append(xs)
    return np.stack(U), np.stack(Y), np.stack(X)


def _diverging_set(ref, n_traj, seed):
    """Trajectories that leave the safe region: larger input, x0 = 0, variable length.

    Mirrors the real ``*_div`` splits — recorded from rest until the state escapes,
    so they are ragged and are fed one per batch. Returns lists, not arrays.
    """
    rng = np.random.default_rng(seed)
    U, Y, X = [], [], []
    while len(U) < n_traj:
        u = DIV_AMP * rng.standard_normal((N_STEPS, ND))
        y, xs, diverged = _simulate(ref, u, np.zeros(NX))
        if not diverged or len(y) < 20:
            continue                            # keep the diverging split diverging
        U.append(u[: len(y)]); Y.append(y); X.append(xs)
    return U, Y, X


@pytest.fixture(scope="module")
def sanity(tmp_path_factory):
    """Reference system + data generated by it + the .npz a warm start reads."""
    ref = _reference_system()
    path = tmp_path_factory.mktemp("sanity") / "reference.npz"
    np.savez(path, **ref)
    return {
        "ref": ref, "path": path,
        "train": _converging_set(ref, N_TRAJ, seed=1),
        "val": _converging_set(ref, 3, seed=2),
        "test": _converging_set(ref, 3, seed=3),
        "train_div": _diverging_set(ref, N_DIV_TRAJ, seed=11),
        "val_div": _diverging_set(ref, 2, seed=12),
        "test_div": _diverging_set(ref, 2, seed=13),
    }


def _model():
    return SimpleLure(nd=ND, ne=NE, nx=NX, nw=NW, activation=CFG.model.activation,
                      ts=TS, custom_params=CFG.model.custom_params)


def _warm_start(sanity, noise, seed=0):
    """A model warm-started from the reference, and the loaders it trains on."""
    tr_u, tr_y, tr_x = sanity["train"]
    va_u, va_y, va_x = sanity["val"]
    te_u, te_y, te_x = sanity["test"]
    tdu, tdy, tdx = sanity["train_div"]
    vdu, vdy, vdx = sanity["val_div"]
    tl, vl, tel, tdl, vdl, tedl, norm = create_dataloaders(
        train_inputs=tr_u, train_outputs=tr_y, train_states=tr_x,
        val_inputs=va_u, val_outputs=va_y, val_states=va_x,
        test_inputs=te_u, test_outputs=te_y, test_states=te_x,
        train_div_inputs=tdu, train_div_outputs=tdy, train_div_states=tdx,
        val_div_inputs=vdu, val_div_outputs=vdy, val_div_states=vdx,
        batch_size=CFG.data.batch_size, sequence_length=SEQ_LEN,
        sequence_stride=CFG.data.sequence_stride, normalize=CFG.data.normalize,
        normalization_method=CFG.data.normalization_method,
        shuffle=CFG.data.shuffle, num_workers=CFG.data.num_workers,
        diverging_batch_size=CFG.data.diverging_batch_size,
    )
    torch.manual_seed(0)
    m = _model()
    rep = m.initialize_parameters(
        tr_u, None, tr_y,
        init_config=replace(CFG.model.initialization, warm_start_path=str(sanity["path"]),
                            warm_start_noise=noise, warm_start_seed=seed),
        normalizer=norm,
    )
    return m, tl, vl, tel, tdl, vdl, norm, rep


def _val_loss(m, vl):
    loss_fn = get_loss_function("mse")
    total, n = 0.0, 0
    with torch.no_grad():
        for batch in vl:
            d, e = batch[0], batch[1]
            yh, _, _ = m(d, x0=None, warmup_steps=WARMUP)
            total += float(loss_fn(yh[:, WARMUP:, :], e[:, WARMUP:, :])); n += 1
    return total / max(n, 1)


# The two hyperparameters that decide whether the gate passes. BOTH differ from the
# Duffing configs, and both differences are findings rather than test-tuning — the
# config file explains each, and TestKnownCouplings pins them.
GATE_LR = CFG.optimizer.learning_rate
GATE_REG = CFG.training.regularization_weight
GATE_EPOCHS = CFG.training.max_epochs
GATE_CLIP = CFG.training.gradient_clip_value

# Every training run here is logged to MLflow so the gate is inspectable next to
# real runs — the loss curves and the distance-to-reference are the whole point of
# the check, and a pass/fail line does not show you those. Runs land in the local
# ./mlruns store (or MLFLOW_TRACKING_URI if set) under this experiment.
# Set SYSID_SANITY_MLFLOW=0 to turn it off, e.g. in CI.
MLFLOW_EXPERIMENT = CFG.mlflow.experiment_name


def _mlflow_enabled() -> bool:
    return os.environ.get("SYSID_SANITY_MLFLOW", "1") not in ("0", "false", "False")


@contextlib.contextmanager
def _mlflow_run(name, params):
    """An MLflow run for one training variant, or a no-op context when disabled.

    Never fails the test: a broken or unreachable tracking store makes the run a
    no-op rather than an error, because this is reporting, not the thing under test.
    """
    if not _mlflow_enabled():
        yield None
        return
    try:
        import mlflow
        mlflow.set_experiment(MLFLOW_EXPERIMENT)
        with mlflow.start_run(run_name=name):
            mlflow.set_tag("suite", "sanity_gate")
            mlflow.set_tag("variant", name)
            mlflow.log_params(params)
            yield mlflow
        return
    except Exception:  # reporting must never break the gate
        pass
    yield None


def _train(m, tl, vl, epochs, lr, tmp_path, div_loader=None, reg_weight=GATE_REG,
           mlf=None, val_fn=None, extra_fn=None):
    tr = Trainer(
        model=m, train_loader=tl, val_loader=vl, train_div_loader=div_loader,
        loss_fn=get_loss_function("mse"),
        optimizer=get_optimizer(m.parameters(), "adam", learning_rate=lr),
        regularization_weight=reg_weight, warmup_steps=WARMUP,
        gradient_clip_value=GATE_CLIP,
        solve_max_s_on_violation=True, device="cpu", mlflow_tracking=False,
        output_dir=str(tmp_path), model_dir=str(tmp_path), log_dir=str(tmp_path),
    )
    history = []
    for epoch in range(1, epochs + 1):
        stats = tr.train_epoch()
        val = (val_fn or _val_loss)(m, vl)
        history.append((stats["pred_loss"], val))
        if mlf is not None:
            mlf.log_metric("train_pred_loss", float(stats["pred_loss"]), step=epoch)
            mlf.log_metric("val_loss", float(val), step=epoch)
            if stats.get("pred_loss_div") is not None:
                mlf.log_metric("train_pred_loss_div", float(stats["pred_loss_div"]), step=epoch)
            mlf.log_metric("s", float(m.s), step=epoch)
            mlf.log_metric("feasible", float(m.check_constraints()), step=epoch)
            for name, value in (extra_fn() if extra_fn else {}).items():
                mlf.log_metric(name, float(value), step=epoch)
    return history


@pytest.fixture(scope="module")
def reference_certificate(sanity):
    """The certificate the GENERATING parameters admit, via the same post_process
    call. The gate compares the recovered certificate against this."""
    m, _, _, _, _, _, _, _ = _warm_start(sanity, noise=0.0)
    return m.post_process(n_grid=8, s_min=0.1, s_max=20.0)


@pytest.fixture(scope="module")
def true_theta_loss(sanity):
    """The loss the GENERATING parameters achieve on this data — the floor every
    assertion below is measured against. It is not exactly zero: the trainer rolls
    out from x0 = 0 while the data starts elsewhere, and `warmup_steps` only hides
    most of that transient."""
    m, _, vl, _, _, _, norm, _ = _warm_start(sanity, noise=0.0)
    return _val_loss(m, vl)


class TestGateConfig:
    """The gate's settings must come from the checked-in YAML and survive loading.

    Guards two failure modes that are otherwise invisible: the config silently
    losing a field (unknown keys are dropped, not raised — grep a run log for
    "Ignoring unknown config field(s)"), and someone retuning the gate by editing
    the constants instead of the file that documents why they are what they are.
    """

    def test_the_settings_come_from_the_config_file(self):
        assert CONFIG_PATH.exists(), f"missing gate config: {CONFIG_PATH}"
        assert GATE_LR == CFG.optimizer.learning_rate
        assert GATE_REG == CFG.training.regularization_weight
        assert GATE_EPOCHS == CFG.training.max_epochs
        assert GATE_CLIP == CFG.training.gradient_clip_value
        assert WARMUP == CFG.training.warmup_steps

    def test_the_fields_the_gate_depends_on_survived_loading(self):
        """A dropped or renamed field would come back as the dataclass default and
        quietly change what the gate measures."""
        assert CFG.model.initialization.method == "warm_start"
        assert CFG.model.initialization.warm_start_units == "physical"
        assert CFG.model.initialization.warm_start_noise > 0.0
        assert CFG.training.gradient_clip_value is not None, (
            "gradient_clip_value went missing; without it a single gradient spike "
            "inflates Adam's second moment and freezes training"
        )
        assert CFG.training.solve_max_s_on_violation is True
        assert CFG.model.custom_params.get("learn_L") is True
        assert set(CFG.model.custom_params["structural_constraints"]) == {"D", "D12"}
        assert CFG.data.shuffle is False, "the gate must be deterministic"
        assert CFG.data.use_diverging_trajectories is True, (
            "the diverging variant of the gate must stay enabled"
        )

    def test_it_is_not_the_working_config(self):
        """The gate must not read genSecSysId-Data — that file is a live experiment
        and the gate is the fixed reference point it is checked against."""
        assert "genSecSysId-Data" not in str(CONFIG_PATH)
        assert CONFIG_PATH.is_relative_to(Path(__file__).parent)


class TestReferenceIsRecoverable:
    """Guards on the fixture itself. If these fail, the rest proves nothing."""

    def test_the_generating_parameters_fit_their_own_data(self, true_theta_loss):
        assert true_theta_loss < 1e-3, (
            f"the reference model does not reproduce its own data (loss "
            f"{true_theta_loss:.3g}); the fixture, not the trainer, is broken"
        )

    def test_the_dead_zone_actually_fires(self, sanity):
        """A reference whose nonlinearity never leaves the band would make this an
        LTI test, and Delta'(z) = 0 means no gradient reaches B2/C2/D21 at all."""
        _, _, _, _, _, _, _, rep = _warm_start(sanity, noise=0.0)
        assert rep.firing_rate is not None and rep.firing_rate > 0.0
        assert rep.max_abs_z > 1.0

    def test_warm_start_lands_on_the_reference_and_is_feasible(self, sanity):
        m, _, _, _, _, _, _, rep = _warm_start(sanity, noise=0.0)
        assert rep.constraints_satisfied and m.check_constraints()

    def test_a_perturbed_start_is_feasible_by_projection(self, sanity):
        """The projection's job: every draw starts inside the certified set."""
        for seed in range(4):
            m, _, _, _, _, _, _, rep = _warm_start(sanity, noise=0.01, seed=seed)
            assert rep.constraints_satisfied, f"seed {seed} started infeasible"
            assert m.check_constraints()


def _run_gate(sanity, true_theta_loss, tmp, variant, div_loader=None):
    """One warm-started training run, followed by the post-processing and
    evaluation stages a real run does, all logged to MLflow.

    Records the distance to the generating parameters before and after, because a
    falling loss is not by itself evidence of recovering the model.
    """
    m, tl, vl, tel, tdl, vdl, norm, rep = _warm_start(sanity, noise=0.002)
    div = tdl if div_loader else None
    su = float(np.asarray(norm.input_std).reshape(-1)[0])
    sy = float(np.asarray(norm.output_std).reshape(-1)[0])
    ref = sanity["ref"]
    true = {"A": ref["A"], "B": ref["B"] * su, "B2": ref["B2"],
            "C": ref["C"] / sy, "C2": ref["C2"]}

    def dist():
        num = sum(np.linalg.norm(getattr(m, k).detach().numpy() - v) ** 2
                  for k, v in true.items())
        den = sum(np.linalg.norm(v) ** 2 for v in true.values())
        return float(np.sqrt(num / den))

    start_loss, start_dist = _val_loss(m, vl), dist()
    params = {"variant": variant, "warm_start_noise": 0.002, "lr": GATE_LR,
              "regularization_weight": GATE_REG, "gradient_clip_value": GATE_CLIP,
              "epochs": GATE_EPOCHS, "nx": NX, "nw": NW, "warmup_steps": WARMUP,
              "use_diverging_trajectories": bool(div_loader),
              "config": CONFIG_PATH.name}
    artifacts = tmp / "artifacts"
    artifacts.mkdir(parents=True, exist_ok=True)

    with _mlflow_run(variant, params) as mlf:
        if mlf is not None:
            mlf.log_metric("true_theta_loss", true_theta_loss)
            mlf.log_metric("start_val_loss", start_loss)
            mlf.log_metric("start_dtheta", start_dist)
            for name, value in (rep.to_metrics() or {}).items():
                mlf.log_metric(f"initialization/{name}", float(value))
        history = _train(m, tl, vl, epochs=GATE_EPOCHS, lr=GATE_LR, tmp_path=tmp,
                         div_loader=div, mlf=mlf, extra_fn=lambda: {"dtheta": dist()})
        end = dist()

        # ---- post-processing: re-solve the certificate over the trained theta ----
        # The same call scripts/post_process.py makes. For a model that converged
        # back to the generator, the certificate it now admits should look like the
        # reference's — a check on the dynamics that does not go through the loss.
        post = m.post_process(n_grid=8, s_min=0.1, s_max=20.0)

        # ---- evaluation on the held-out split, WITH artifacts ----
        # save_files=True writes predictions/targets/inputs/states + the metrics
        # json, exactly as scripts/evaluate.py does, so the MLflow run carries the
        # same evidence a real run does rather than just scalars.
        ev = Evaluator(m, device="cpu", output_dir=str(artifacts / "evaluation"),
                       warmup_steps=WARMUP)
        results = ev.evaluate(tel, normalizer=norm, print_results=False, save_files=True)
        metrics = {k: v for k, v in results["metrics"].items()
                   if k != "per_step" and np.isscalar(v)}
        div_metrics = {}
        if vdl is not None:
            dres = ev.evaluate_diverging(vdl, normalizer=norm, print_results=False,
                                         save_files=True)
            div_metrics = {k: v for k, v in (dres.get("metrics_div") or {}).items()
                           if np.isscalar(v)}

        figures = _make_plots(m, vl, vdl, norm, artifacts, variant)

        if mlf is not None:
            for key in ("s_opt", "success", "constraints_satisfied"):
                if key in post and np.isscalar(post[key]):
                    mlf.log_metric(f"post_process/{key}", float(post[key]))
            for key, value in (post.get("max_s") or {}).items():
                if np.isscalar(value) and value is not None:
                    mlf.log_metric(f"post_process/max_s/{key}", float(value))
            for key, value in metrics.items():
                mlf.log_metric(f"test/{key}", float(value))
            for key, value in div_metrics.items():
                mlf.log_metric(f"test_div/{key}", float(value))
            best = min(v for _, v in history)
            mlf.log_metric("best_val_loss", best)
            mlf.log_metric("final_val_loss", history[-1][1])
            mlf.log_metric("end_dtheta", end)
            mlf.log_metric("best_over_true", best / max(true_theta_loss, 1e-30))
            mlf.set_tag("gate_passed", str(best < 10 * true_theta_loss))
            try:
                mlf.log_artifacts(str(artifacts), "outputs")
            except Exception:
                pass

    return {"model": m, "history": history, "start_loss": start_loss,
            "start_dist": start_dist, "end_dist": end, "post": post,
            "test_metrics": metrics, "test_div_metrics": div_metrics,
            "figures": figures, "artifacts": artifacts}


def _make_plots(m, vl, vdl, norm, artifacts, variant):
    """Prediction plots for the run, saved next to the evaluation artifacts.

    Uses the Trainer's own plotting so the figures match what a real run produces.
    Plotting is reporting, not the thing under test: a failure here is recorded and
    swallowed rather than failing the gate.
    """
    plots = artifacts / "plots"
    plots.mkdir(parents=True, exist_ok=True)
    made = []
    plotter = Trainer(
        model=m, train_loader=vl, val_loader=vl, val_div_loader=vdl,
        loss_fn=get_loss_function("mse"),
        optimizer=get_optimizer(m.parameters(), "adam", learning_rate=GATE_LR),
        warmup_steps=WARMUP, device="cpu", mlflow_tracking=False,
        output_dir=str(plots), model_dir=str(plots), log_dir=str(plots),
    )
    for fn, name in ((plotter.plot_trajectories, f"{variant}_predictions"),
                     (plotter.plot_trajectories_div, f"{variant}_predictions_div")):
        try:
            fn(normalizer=norm, name=name)
            made.extend(str(q) for q in plots.rglob(f"*{name}*"))
        except Exception as exc:
            made.append(f"FAILED {name}: {exc}")
    return made


@pytest.fixture(scope="module")
def gate_run(sanity, true_theta_loss, tmp_path_factory):
    """The gate: warm start, converging trajectories only."""
    return _run_gate(sanity, true_theta_loss, tmp_path_factory.mktemp("gate"), "gate")


@pytest.fixture(scope="module")
def gate_div_run(sanity, true_theta_loss, tmp_path_factory):
    """The same gate with the DIVERGING trajectories in the training loop.

    The one the config's ``use_diverging_trajectories`` describes: a warm start must
    converge back with the diverging pass running too. It needs
    ``gradient_clip_value`` — without it a single spike from a diverging rollout
    inflates Adam's second moment and freezes the effective step size for ~1000
    steps (see TestKnownCouplings)."""
    return _run_gate(sanity, true_theta_loss, tmp_path_factory.mktemp("gate_div"),
                     "gate_diverging", div_loader=True)


class TestConvergesBackToTheGeneratingModel:
    """The gate. A near-optimal, feasible start must be driven back to the optimum."""

    def test_reaches_the_true_theta_loss(self, gate_run, true_theta_loss):
        start = gate_run["start_loss"]
        vals = [v for _, v in gate_run["history"]]
        best = min(vals)

        assert best < start, (
            f"training did not improve on the warm start at all "
            f"(start {start:.4g}, best {best:.4g})"
        )
        # The floor is the generating parameters' own loss. An order of magnitude of
        # slack covers optimizer noise; the observed ratio is ~2x.
        assert best < 10 * true_theta_loss, (
            f"warm-started training did not converge back to the generating model: "
            f"best val_loss {best:.4g} vs true-theta {true_theta_loss:.4g} "
            f"(start {start:.4g}, final {vals[-1]:.4g}). The optimum is known, "
            f"representable, and adjacent to the start — so the training loop is at "
            f"fault, not the init, the model class or the data."
        )

    def test_stays_feasible_and_finite(self, gate_run):
        """No NaN/Inf blow-up and the certificate still holds at the end. A rollout
        that explodes mid-epoch is the failure mode this catches."""
        m = gate_run["model"]
        for ep, (pred, val) in enumerate(gate_run["history"], 1):
            assert np.isfinite(pred), f"epoch {ep}: pred_loss is {pred}"
            assert np.isfinite(val), f"epoch {ep}: val_loss is {val}"
            assert pred < 1e3, f"epoch {ep}: pred_loss blew up to {pred:.3g}"
        assert m.check_constraints(), "training ended outside the feasible set"
        assert all(torch.isfinite(p).all() for p in m.parameters())

    def test_theta_does_not_wander_off(self, gate_run):
        """theta must stay in the neighbourhood it started in.

        Deliberately a loose bound, not "theta converges to the reference". The Lure
        realization has a continuous symmetry: for any invertible T,
        ``(A, B, B2, C, C2) -> (TAT^-1, TB, TB2, CT^-1, C2T^-1)`` is the same
        input-output system with the same loss. So theta is identifiable only up to
        similarity and there is no reason for it to return to these exact matrices —
        the behaviour is what converges, which is what
        :meth:`test_reaches_the_true_theta_loss` asserts. What this catches is the
        other failure mode: the loss falling while theta runs away entirely (the
        collapsed "predict ~0" basin sits far from the reference).
        """
        before, after = gate_run["start_dist"], gate_run["end_dist"]
        assert after < 3.0 * before, (
            f"theta wandered far from the generating parameters: "
            f"||dtheta||/||theta|| {before:.5f} -> {after:.5f}"
        )


class TestPostProcessingAndEvaluation:
    """The stages after training: re-solve the certificate, then evaluate.

    Both are logged to MLflow on the ``gate`` run, so the experiment shows the whole
    pipeline — init report, training curves, final certificate, test metrics —
    rather than a bare pass/fail.
    """

    def test_post_processing_succeeds_and_leaves_the_model_certified(self, gate_run):
        post = gate_run["post"]
        assert post["success"], f"post_process failed: {post.get('status')}"
        assert post["constraints_satisfied"]
        assert gate_run["model"].check_constraints()

    def test_the_recovered_certificate_matches_the_reference_one(
        self, gate_run, reference_certificate
    ):
        """Independent of the loss: a model that recovered the generating dynamics
        must admit a similar certificate. Loose factors — the certificate is a
        property of theta, and theta is only identified up to similarity, so the
        scale s and the ellipsoid volume are compared by order of magnitude."""
        got, ref = gate_run["post"]["max_s"], reference_certificate["max_s"]
        assert got["s"] == pytest.approx(ref["s"], rel=0.5), (
            f"recovered MaxS scale s={got['s']:.4g} vs reference {ref['s']:.4g}"
        )
        assert 0.1 < got["volume"] / ref["volume"] < 10.0, (
            f"recovered certified volume {got['volume']:.4g} vs reference "
            f"{ref['volume']:.4g}"
        )
        assert got["max_eig_F"] < 0, "recovered certificate does not satisfy the LMI"

    def test_test_split_metrics_are_near_the_noise_floor(self, gate_run):
        """The data is generated by the model class with no observation noise, so a
        recovered model should predict the held-out split almost exactly. rmse is in
        PHYSICAL units; compare it against the split's own output scale."""
        metrics = gate_run["test_metrics"]
        assert "rmse" in metrics, f"expected rmse in {sorted(metrics)}"
        assert np.isfinite(metrics["rmse"])
        assert metrics["rmse"] < 0.05, (
            f"held-out rmse {metrics['rmse']:.4g} is far above the noise floor; the "
            f"model did not recover the generating dynamics"
        )


class TestDivergingTrajectoriesAlsoConverge:
    """The diverging half of the gate: warm start + the diverging pass.

    Diverging trajectories are recorded from x0 = 0 until the state escapes, and
    they are what ``use_diverging_trajectories`` adds to training. A near-optimal
    start must survive them: their gradients are much larger (a diverging rollout
    accumulates sensitivity where a converging one contracts), which is exactly what
    ``gradient_clip_value`` is there to bound.
    """

    def test_the_fixture_actually_diverges(self, sanity):
        """Guards the fixture. A globally stable reference could never produce a
        diverging trajectory, and this whole class would be vacuous — an earlier
        version of the fixture had rho(A + B2 C2) = 0.95 and was silently stable."""
        ref = sanity["ref"]
        rho_lin = max(abs(np.linalg.eigvals(ref["A"])))
        rho_sat = max(abs(np.linalg.eigvals(ref["A"] + ref["B2"] @ ref["C2"])))
        assert rho_lin < 1.0 < rho_sat, (
            f"reference must be stable in the dead band and unstable outside it; "
            f"got rho(A)={rho_lin:.4f}, rho(A+B2C2)={rho_sat:.4f}"
        )
        div_u, div_y, _ = sanity["train_div"]
        assert len(div_u) > 0
        conv_max = np.abs(sanity["train"][1]).max()
        assert max(np.abs(y).max() for y in div_y) > 10 * conv_max, (
            "the diverging split does not leave the converging split's range"
        )
        assert len({len(u) for u in div_u}) > 1, "diverging split should be ragged"

    def test_converges_with_the_diverging_pass_running(
        self, gate_div_run, true_theta_loss
    ):
        vals = [v for _, v in gate_div_run["history"]]
        best = min(vals)
        assert best < gate_div_run["start_loss"]
        assert best < 10 * true_theta_loss, (
            f"warm-started training with diverging trajectories did not converge "
            f"back: best val_loss {best:.4g} vs true-theta {true_theta_loss:.4g} "
            f"(start {gate_div_run['start_loss']:.4g}). Check that "
            f"gradient_clip_value is set — without it one spike from a diverging "
            f"rollout freezes Adam."
        )

    def test_it_is_not_much_worse_than_without_them(self, gate_run, gate_div_run):
        """The diverging pass should cost little. Measured ~2.5x true-theta with it
        vs ~2.2x without, so a factor of 5 is generous slack on a real regression."""
        with_div = min(v for _, v in gate_div_run["history"])
        without = min(v for _, v in gate_run["history"])
        assert with_div < 5.0 * without, (
            f"the diverging pass degraded convergence: best val_loss {with_div:.4g} "
            f"with it vs {without:.4g} without"
        )

    def test_stays_feasible_and_finite(self, gate_div_run):
        m = gate_div_run["model"]
        for ep, (pred, val) in enumerate(gate_div_run["history"], 1):
            assert np.isfinite(pred) and np.isfinite(val), f"epoch {ep}: {pred}, {val}"
        assert m.check_constraints()
        assert all(torch.isfinite(p).all() for p in m.parameters())


class TestArtifacts:
    """The run must leave the same evidence a real run does, not just scalars."""

    def test_evaluation_artifacts_are_written(self, gate_run):
        ev = gate_run["artifacts"] / "evaluation"
        for name in ("predictions.npy", "targets.npy", "inputs.npy",
                     "evaluation_results.json"):
            assert (ev / name).exists(), f"missing evaluation artifact: {name}"
            assert (ev / name).stat().st_size > 0, f"empty artifact: {name}"

    def test_prediction_plots_are_produced(self, gate_run):
        made = gate_run["figures"]
        failures = [f for f in made if f.startswith("FAILED")]
        assert not failures, f"plotting failed: {failures}"
        pngs = list((gate_run["artifacts"] / "plots").rglob("*.png"))
        assert pngs, "no prediction plots were written"
        assert all(q.stat().st_size > 0 for q in pngs)

    def test_diverging_run_reports_its_own_metrics(self, gate_div_run):
        """evaluate_diverging pools all timesteps of the ragged trajectories."""
        assert gate_div_run["test_div_metrics"], "no diverging evaluation metrics"
        assert np.isfinite(list(gate_div_run["test_div_metrics"].values())).all()


class TestKnownCouplings:
    """Why the gate runs at lr=5e-5 and reg_weight=1e-5 rather than the Duffing
    configs' 5e-3 / 1e-3. Both are documented as tests so they are not rediscovered.

    These assert that a KNOWN LIMITATION still bites. If someone makes the training
    loop robust to either (gradient normalization, per-parameter scaling, a trust
    region, scaling the barrier by the prediction loss) these start failing — that
    is a fix, not a regression: delete the test and relax the gate's setting.
    """

    def test_a_large_lr_destroys_a_near_perfect_start(
        self, sanity, true_theta_loss, tmp_path
    ):
        """Adam's step is ~lr per element regardless of that element's magnitude.
        Here B entries are ~5e-3 and rho(A) is 0.95, so lr=5e-3 is a 100% change to
        B and enough to move A a long way; the rollout then leaves the region where
        the linearization is meaningful and the loss explodes."""
        m, tl, vl, _, _, _, _, _ = _warm_start(sanity, noise=0.002)
        with _mlflow_run("large_lr", {"variant": "large_lr", "lr": 5e-3,
                                      "regularization_weight": GATE_REG,
                                      "warm_start_noise": 0.002, "epochs": 5}) as mlf:
            history = _train(m, tl, vl, epochs=5, lr=5e-3, tmp_path=tmp_path, mlf=mlf)
            best = min(v for _, v in history)
            if mlf is not None:
                mlf.log_metric("best_val_loss", best)
                mlf.log_metric("true_theta_loss", true_theta_loss)
        assert best > 10 * true_theta_loss, (
            f"lr=5e-3 now recovers the warm start (best val_loss {best:.4g} vs "
            f"true-theta {true_theta_loss:.4g}). If the training loop was made "
            f"robust to the step size, delete this test and relax GATE_LR."
        )

    def test_the_barrier_weight_dominates_near_the_optimum(
        self, sanity, true_theta_loss, gate_run, tmp_path
    ):
        """The barrier is O(100) while pred_loss near the optimum is O(1e-4), so at
        reg_weight=1e-3 it contributes ~600x the prediction loss and the optimizer
        minimizes the barrier instead of the fit. The certificate still needs a
        barrier — at weight 0 the run ends INFEASIBLE — so the weight has to be
        scaled against the prediction loss, not fixed."""
        m, tl, vl, _, _, _, _, _ = _warm_start(sanity, noise=0.002)
        barrier = float(m.get_regularization_loss())
        pred = _val_loss(m, vl)
        assert 1e-3 * barrier > 100 * pred, (
            f"the barrier no longer dominates at reg_weight=1e-3 "
            f"(barrier {barrier:.4g}, pred {pred:.4g})"
        )
        with _mlflow_run("large_reg", {"variant": "large_reg", "lr": GATE_LR,
                                       "regularization_weight": 1e-3,
                                       "warm_start_noise": 0.002,
                                       "epochs": GATE_EPOCHS}) as mlf:
            history = _train(m, tl, vl, epochs=GATE_EPOCHS, lr=GATE_LR,
                             tmp_path=tmp_path, reg_weight=1e-3, mlf=mlf)
            best = min(v for _, v in history)
            if mlf is not None:
                mlf.log_metric("best_val_loss", best)
                mlf.log_metric("true_theta_loss", true_theta_loss)
        gate_best = min(v for _, v in gate_run["history"])
        assert best > 2.0 * gate_best, (
            f"reg_weight=1e-3 is no longer worse than the gate's {GATE_REG:g} "
            f"(best val_loss {best:.4g} vs {gate_best:.4g}). If the barrier is now "
            f"scaled relative to the prediction loss, delete this test and relax "
            f"GATE_REG."
        )


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
