"""Tests for the warm-start initialization (``initialization.method='warm_start'``).

The sanity check: load a known-good theta from an .npz, perturb it, and PROJECT it
back onto the set certified by the undisturbed reference's own certificate. On data
generated by that same model, training then starts near the optimum and feasible, so
a slow or non-converging run indicts the training loop rather than the init.

Three things pinned here, because each is easy to get silently wrong:

* **Unit conversion.** The stored theta is identified on raw data; the model works
  in normalized units. B and D21 scale by ``input_std``, C and D12 by
  ``1/output_std``, D by their ratio, and A/B2/C2 are invariant.
* **Projection, not re-solve.** The certificate comes from the UNDISTURBED theta
  and is then held fixed; the perturbed theta is moved the smallest distance that
  satisfies it. A draw that is already feasible must come back untouched.
* **theta is not repaired by the D21 bootstrap**, which would move the input map
  off the reference and destroy what the check measures.
"""

import numpy as np
import pytest
import torch

from sysid.config import InitializationConfig
from sysid.models.constrained_rnn import SimpleLure
from sysid.optimization import LureCertificateSynthesizer

from tests.solver_utils import requires_mosek


class _Normalizer:
    """Minimal scale_only normalizer stand-in."""

    def __init__(self, input_std=2.0, output_std=4.0):
        self.input_std = np.array([input_std])
        self.output_std = np.array([output_std])

    def transform_inputs(self, u):
        return np.asarray(u) / self.input_std

    def transform_outputs(self, y):
        return np.asarray(y) / self.output_std


def _reference_npz(tmp_path, nx=2, nz=3, nd=1, ne=1, seed=0):
    """A small, comfortably stable reference Lure system written as an .npz."""
    rng = np.random.default_rng(seed)
    ref = {
        "A": np.array([[0.9, 0.05], [-0.05, 0.88]]),
        "B": 0.05 * np.ones((nx, nd)),
        "B2": 0.02 * rng.standard_normal((nx, nz)),
        "C": np.array([[1.0, 0.0]]),
        "C2": 0.5 * rng.standard_normal((nz, nx)),
        "D": np.zeros((ne, nd)),
        "D12": np.zeros((ne, nz)),
        "D21": 0.1 * np.ones((nz, nd)),
        "nx": nx, "nz": nz, "nu": nd, "ny": ne,
    }
    path = tmp_path / "ref.npz"
    np.savez(path, **ref)
    return path, ref


def _model(nx=2, nw=3, **custom):
    params = {"learn_L": True}
    params.update(custom)
    return SimpleLure(nd=1, ne=1, nx=nx, nw=nw, activation="dzn", ts=0.05,
                      custom_params=params)


def _cfg(path, **kw):
    base = dict(method="warm_start", warm_start_path=str(path),
                warm_start_noise=0.0, warm_start_seed=0)
    base.update(kw)
    return InitializationConfig(**base)


def _load_into(m, cfg, norm=None):
    """Load the reference and write it, the way _warm_start_certified step 1 does."""
    clean = m._warm_start_load(cfg, norm)
    for name, value in clean.items():
        m._set_param_data(name, value)
    return clean


class TestUnitConversion:
    """physical -> model units. Getting this wrong is silent, so it is pinned."""

    def test_normalized_units_load_the_stored_theta_verbatim(self, tmp_path):
        path, ref = _reference_npz(tmp_path)
        m = _model()
        _load_into(m, _cfg(path, warm_start_units="normalized"))
        for name in ("A", "B", "B2", "C", "C2", "D21"):
            assert np.allclose(getattr(m, name).detach().numpy(), ref[name], atol=1e-12), name

    def test_physical_units_apply_the_normalizer_scaling(self, tmp_path):
        path, ref = _reference_npz(tmp_path)
        m = _model()
        _load_into(m, _cfg(path, warm_start_units="physical"),
                   _Normalizer(input_std=2.0, output_std=4.0))
        # B, D21 scale by input_std; C, D12 by 1/output_std; A, B2, C2 invariant.
        assert np.allclose(m.B.detach().numpy(), ref["B"] * 2.0)
        assert np.allclose(m.D21.detach().numpy(), ref["D21"] * 2.0)
        assert np.allclose(m.C.detach().numpy(), ref["C"] / 4.0)
        assert np.allclose(m.A.detach().numpy(), ref["A"])
        assert np.allclose(m.B2.detach().numpy(), ref["B2"])
        assert np.allclose(m.C2.detach().numpy(), ref["C2"])

    def test_scaling_makes_the_normalized_model_match_the_physical_one(self, tmp_path):
        """The point of the conversion: fed normalized inputs, the scaled model must
        produce the physical system's output divided by output_std."""
        path, _ = _reference_npz(tmp_path)
        norm = _Normalizer(input_std=2.0, output_std=4.0)
        phys = _model();   _load_into(phys, _cfg(path, warm_start_units="normalized"))
        scaled = _model(); _load_into(scaled, _cfg(path, warm_start_units="physical"), norm)

        u = 0.3 * torch.randn(2, 25, 1, dtype=phys.C2.dtype)
        with torch.no_grad():
            y_phys, _, _ = phys(u, x0=None, warmup_steps=0)
            y_norm, _, _ = scaled(
                torch.tensor(norm.transform_inputs(u.numpy()), dtype=scaled.C2.dtype),
                x0=None, warmup_steps=0)
        assert torch.allclose(y_norm, y_phys / 4.0, atol=1e-9)

    def test_physical_units_without_a_normalizer_is_an_error(self, tmp_path):
        path, _ = _reference_npz(tmp_path)
        with pytest.raises(ValueError, match="needs a normalizer"):
            _model()._warm_start_load(_cfg(path, warm_start_units="physical"), None)

    def test_unknown_units_rejected(self, tmp_path):
        path, _ = _reference_npz(tmp_path)
        with pytest.raises(ValueError, match="warm_start_units"):
            _model()._warm_start_load(_cfg(path, warm_start_units="raw"), None)


class TestPerturbation:
    """theta <- theta + noise * rms(theta) * N(0,1), per block."""

    def test_noise_scales_the_offset_and_is_seed_reproducible(self, tmp_path):
        path, _ = _reference_npz(tmp_path)
        m = _model()
        clean = m._warm_start_load(_cfg(path, warm_start_units="normalized"), None)

        def rel(noise, seed=0):
            p = m._warm_start_perturb(clean, noise, seed)
            return float(torch.linalg.norm(p["A"] - clean["A"]) / torch.linalg.norm(clean["A"]))

        assert rel(0.05) == pytest.approx(5 * rel(0.01), rel=1e-6)
        a = m._warm_start_perturb(clean, 0.02, 7)
        b = m._warm_start_perturb(clean, 0.02, 7)
        assert torch.equal(a["A"], b["A"]) and torch.equal(a["C2"], b["C2"])

    def test_different_seeds_give_different_draws(self, tmp_path):
        path, _ = _reference_npz(tmp_path)
        m = _model()
        clean = m._warm_start_load(_cfg(path, warm_start_units="normalized"), None)
        assert not torch.equal(
            m._warm_start_perturb(clean, 0.02, 1)["A"],
            m._warm_start_perturb(clean, 0.02, 2)["A"],
        )

    def test_all_zero_block_stays_exactly_zero(self, tmp_path):
        """rms == 0 -> no perturbation. D and D12 are exactly zero in the reference
        Duffing model, and a relative perturbation of zero is still zero."""
        path, _ = _reference_npz(tmp_path)
        m = _model()
        clean = m._warm_start_load(_cfg(path, warm_start_units="normalized"), None)
        noisy = m._warm_start_perturb(clean, 0.1, 0)
        assert torch.count_nonzero(noisy["D"]) == 0
        assert torch.count_nonzero(noisy["D12"]) == 0

    def test_zero_noise_is_the_identity(self, tmp_path):
        path, _ = _reference_npz(tmp_path)
        m = _model()
        clean = m._warm_start_load(_cfg(path, warm_start_units="normalized"), None)
        noisy = m._warm_start_perturb(clean, 0.0, 0)
        assert all(torch.equal(noisy[k], clean[k]) for k in clean)


class TestStructuralConstraints:
    def test_fixed_parameter_is_not_loaded(self, tmp_path):
        path, ref = _reference_npz(tmp_path)
        m = _model(structural_constraints={"D21": {"fixed": True, "value": 0.0}})
        clean = _load_into(m, _cfg(path, warm_start_units="normalized"))
        assert "D21" not in clean
        assert torch.count_nonzero(m.D21) == 0                 # kept its fixed value
        assert np.allclose(m.A.detach().numpy(), ref["A"])     # others still loaded


class TestValidation:
    def test_missing_file_names_the_path(self, tmp_path):
        with pytest.raises(FileNotFoundError, match="warm_start_path"):
            _model()._warm_start_load(_cfg(tmp_path / "nope.npz"), None)

    def test_dimension_mismatch_is_caught_with_a_useful_message(self, tmp_path):
        path, _ = _reference_npz(tmp_path, nz=3)
        with pytest.raises(ValueError, match="nw/nz"):
            _model(nw=5)._warm_start_load(_cfg(path, warm_start_units="normalized"), None)

    def test_method_warm_start_without_a_path_is_rejected(self):
        with pytest.raises(ValueError, match="warm_start_path"):
            _model().initialize_parameters(
                np.zeros((2, 5, 1)), None, np.zeros((2, 5, 1)),
                init_config=InitializationConfig(method="warm_start"),
                normalizer=_Normalizer())

    def test_unknown_method_still_rejected(self):
        with pytest.raises(ValueError, match="Unknown initialization method"):
            _model().initialize_parameters(
                np.zeros((2, 5, 1)), None, np.zeros((2, 5, 1)),
                init_config=InitializationConfig(method="esn"),
                normalizer=_Normalizer())

    def test_config_defaults(self):
        cfg = InitializationConfig()
        assert cfg.method == "identity"
        assert cfg.warm_start_path is None
        assert cfg.warm_start_units == "physical"
        assert cfg.warm_start_noise == 0.001
        assert cfg.warm_start_seed is None


@requires_mosek
class TestProjection:
    """``project_theta``: nearest theta the FIXED certificate still certifies."""

    def _certified(self, tmp_path):
        path, ref = _reference_npz(tmp_path)
        m = _model()
        _load_into(m, _cfg(path, warm_start_units="normalized"))
        synth = m._synth()
        cert = synth.max_s()
        assert cert is not None, "reference model must be certifiable"
        return m, synth, cert, ref

    def test_feasible_target_is_returned_unchanged(self, tmp_path):
        """A projection is idempotent on its own feasible set: the reference theta
        already satisfies its own certificate, so it must come back untouched."""
        m, synth, cert, ref = self._certified(tmp_path)
        target = {n: getattr(m, n).detach().numpy()
                  for n in LureCertificateSynthesizer.THETA_IN_F}
        out = synth.project_theta(target, cert.P, cert.L, cert.M)
        for name in out:
            assert np.allclose(out[name], target[name], atol=1e-5), name

    def test_projection_of_an_infeasible_draw_is_certified(self, tmp_path):
        """The point of the exercise: a draw that breaks the LMI comes back feasible,
        under the ORIGINAL certificate (which is never re-solved)."""
        m, synth, cert, ref = self._certified(tmp_path)
        target = {n: getattr(m, n).detach().numpy()
                  for n in LureCertificateSynthesizer.THETA_IN_F}
        target["A"] = target["A"] * 1.25          # push rho(A) out; breaks F < 0
        assert synth.max_eig_F(cert.P, cert.L, cert.M, **target) > 0

        out = synth.project_theta(target, cert.P, cert.L, cert.M)
        assert out is not None
        merged = dict(target); merged.update(out)
        assert synth.max_eig_F(cert.P, cert.L, cert.M, **merged) <= 0

    def test_projection_moves_only_the_free_blocks(self, tmp_path):
        m, synth, cert, ref = self._certified(tmp_path)
        target = {n: getattr(m, n).detach().numpy()
                  for n in LureCertificateSynthesizer.THETA_IN_F}
        target["A"] = target["A"] * 1.25
        out = synth.project_theta(target, cert.P, cert.L, cert.M, free=["A", "B2"])
        assert set(out) == {"A", "B2"}

    def test_rejects_blocks_that_are_not_in_the_lmi(self, tmp_path):
        m, synth, cert, ref = self._certified(tmp_path)
        target = {n: getattr(m, n).detach().numpy()
                  for n in LureCertificateSynthesizer.THETA_IN_F}
        with pytest.raises(ValueError, match="do not appear in F"):
            synth.project_theta(target, cert.P, cert.L, cert.M, free=["C"])

    def test_rejects_an_incomplete_target(self, tmp_path):
        m, synth, cert, ref = self._certified(tmp_path)
        with pytest.raises(ValueError, match="missing"):
            synth.project_theta({"A": np.eye(2)}, cert.P, cert.L, cert.M)


@requires_mosek
class TestCertifiedWarmStart:
    """The full path: load -> certify reference -> perturb -> project -> apply."""

    def _init(self, tmp_path, **kw):
        path, ref = _reference_npz(tmp_path)
        m = _model()
        rng = np.random.default_rng(0)
        rep = m.initialize_parameters(
            0.1 * rng.standard_normal((3, 40, 1)), None,
            0.1 * rng.standard_normal((3, 40, 1)),
            init_config=_cfg(path, warm_start_units="normalized", **kw),
            normalizer=_Normalizer(input_std=1.0, output_std=1.0))
        return m, rep, ref

    def test_zero_noise_leaves_theta_exactly_at_the_reference(self, tmp_path):
        m, rep, ref = self._init(tmp_path, warm_start_noise=0.0)
        assert rep.constraints_satisfied and m.check_constraints()
        for name in ("A", "B", "B2", "C", "C2", "D21"):
            assert np.allclose(getattr(m, name).detach().numpy(), ref[name], atol=1e-12), name

    def test_perturbed_start_is_feasible_and_near_the_reference(self, tmp_path):
        m, rep, ref = self._init(tmp_path, warm_start_noise=0.02)
        assert rep.constraints_satisfied and m.check_constraints()
        rel = np.linalg.norm(m.A.detach().numpy() - ref["A"]) / np.linalg.norm(ref["A"])
        assert 0.0 < rel < 0.1

    def test_offsets_reach_the_init_report(self, tmp_path):
        m, rep, ref = self._init(tmp_path, warm_start_noise=0.01)
        assert rep.warm_start_offsets["A"] > 0.0
        assert "warm_start_offset/A" in rep.to_metrics()

    def test_an_uncertifiable_reference_is_reported_as_such(self, tmp_path, monkeypatch):
        """If even the UNDISTURBED theta fails, the file and the model class
        disagree — that must be said plainly, not blamed on the noise."""
        monkeypatch.setattr(LureCertificateSynthesizer, "max_s", lambda self, *a, **k: None)
        with pytest.raises(RuntimeError, match="UNDISTURBED reference theta"):
            self._init(tmp_path, warm_start_noise=0.01)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
